'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Honors_Project_2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tim Berners-Lee is the founder of the World Wide Web, director of the World Wide Web Consortium (W3C), and founded the World Wide Web Foundation..
        '''</summary>
        Friend ReadOnly Property bernersLeeInfo() As String
            Get
                Return ResourceManager.GetString("bernersLeeInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gaben() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gaben", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gabe Newell is the Managing Director of Valve. He is the creator of Steam and of many games on the platform..
        '''</summary>
        Friend ReadOnly Property gabenInfo() As String
            Get
                Return ResourceManager.GetString("gabenInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Richard Stallman is an activist for Free Software and a computer programmer. He launched the GNU project, which spawned the GNU Compiler Collection and Emacs, wrote the GNU General Public License (GPL), launched the Free Software Foundation (FSF), and pioneered the concept of copyleft..
        '''</summary>
        Friend ReadOnly Property RMSInfo() As String
            Get
                Return ResourceManager.GetString("RMSInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linus Torvalds is the main force behind the creation of the Linux kernel. He is now the coordinator of the project. He is also the creator of Git, a version control system which is widely used in the field of computer science..
        '''</summary>
        Friend ReadOnly Property torvaldsInfo() As String
            Get
                Return ResourceManager.GetString("torvaldsInfo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
